fixeed

diff --git a/bin/git-submodule-rm b/bin/git-submodule-rm
--- a/bin/git-submodule-rm
+++ b/bin/git-submodule-rm
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # $File: ${DOTDIR}/bin/git-submodule-rm
-# $Date: 2011-09-19T22:02:51+0900$
+# $Date: 2012-02-19T16:48:24+0900$
 # vim:filetype=zsh:tabstop=2:shiftwidth=2:fdm=marker:
 
 ! which git >/dev/null 2>&1 && exit 1
@@ -14,23 +14,25 @@ commit=false
 submodule_rm() {
   [ $# -eq 0 ] && exit 1
 
+  dir=${1%/}
+
   while [ $# -gt 0 ];
   do
-    path=`git config --file .gitmodules --get submodule.$1.path`
+    path=`git config --file .gitmodules --get submodule.$dir.path`
     if [ -n "$path" ]; then
       git rm $quiet --cached "$path"
       if [ -z "$cached" ]; then
         rm -rf "$path"
       fi
-      git config --file .gitmodules --remove-section submodule.$1
+      git config --file .gitmodules --remove-section submodule.$dir
       git add .gitmodules
 
       if $commit ; then
-        git commit -m "Removed submodule $1"
+        git commit -m "Removed submodule $dir"
       fi
 
     else
-      echo "Error: No available submodule $1" >&2
+      echo "Error: No available submodule $dir" >&2
     fi
     shift
   done
